### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant com.github.messenger4j.receive.events.AttachmentMessageEvent.AttachmentType.FALLBACK

### ISSUE THREAD

**Issue by jgarcia-controltechcg** [messenger4j/messenger4j#23]
Greetings to all.

My application is receiving the following payload from the Messenger Platform:

{"object":"page","entry":[{"id":"_999999999999999_","time":1500492242330,"messaging":[{"sender":{"id":"_9999999999999999_"},"recipient":{"id":"_9999999999999999_"},"timestamp":1500488692699,"message":{"mid":"mid.$_XXXXXXXXXXXXXXXXXXXXXXXXXX_-HQ","seq":59099,"attachments":[{"title":"","url":"https:\/\/www.facebook.com\/VixExplora\/photos\/a.205505322826303.50136.108929955817174\/1490843614292461\/?type=3","**type**":"**fallback**","payload":null}]}}]}]} 

But is throwing the following exception:

java.lang.IllegalArgumentException: No enum constant com.github.messenger4j.receive.events.AttachmentMessageEvent.AttachmentType.FALLBACK
	at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_121]
	at com.github.messenger4j.receive.events.AttachmentMessageEvent$AttachmentType.valueOf(AttachmentMessageEvent.java:177) ~[messenger4j-0.8.0.jar:na]
	at com.github.messenger4j.receive.events.AttachmentMessageEvent$Attachment.fromJson(AttachmentMessageEvent.java:120) ~[messenger4j-0.8.0.jar:na]
	at com.github.messenger4j.receive.events.AttachmentMessageEvent$Attachment.access$000(AttachmentMessageEvent.java:113) ~[messenger4j-0.8.0.jar:na]
	at com.github.messenger4j.receive.events.AttachmentMessageEvent.fromJson(AttachmentMessageEvent.java:67) ~[messenger4j-0.8.0.jar:na]
	at com.github.messenger4j.receive.callers.AttachmentMessageEventHandlerCaller.createEventFromJson(AttachmentMessageEventHandlerCaller.java:39) ~[messenger4j-0.8.0.jar:na]
	at com.github.messenger4j.receive.callers.AttachmentMessageEventHandlerCaller.createEventFromJson(AttachmentMessageEventHandlerCaller.java:23) ~[messenger4j-0.8.0.jar:na]
	at com.github.messenger4j.receive.callers.EventHandlerCaller.callHandlerIfResponsibleForEvent(EventHandlerCaller.java:60) ~[messenger4j-0.8.0.jar:na]
	at com.github.messenger4j.receive.MessengerReceiveClientImpl.processMessagingEvent(MessengerReceiveClientImpl.java:158) ~[messenger4j-0.8.0.jar:na]
	at com.github.messenger4j.receive.MessengerReceiveClientImpl.processEntry(MessengerReceiveClientImpl.java:151) ~[messenger4j-0.8.0.jar:na]
	at com.github.messenger4j.receive.MessengerReceiveClientImpl.processCallbackPayload(MessengerReceiveClientImpl.java:144) ~[messenger4j-0.8.0.jar:na]

The platform documentaton (https://developers.facebook.com/docs/messenger-platform/webhook-reference/message), in "Message with fallback attachment from link scraping" says:

attachment object: type: audio, **fallback**, file, image, location or video.

Please review this issue. I will await your recommendations. Thank you.

**Comment by maxgrabenhorst** [comment]
Hi, thanks for reporting this.
This is a known bug and will be fixed with the next version.

**Comment by maxgrabenhorst** [comment]
Hi,
messenger4j 1.0.0-M1 is out. In this version your bug is now fixed.
