### ISSUE TITLE
NPE in okhttp3 client

### ISSUE THREAD

**Issue by ginccc** [messenger4j/messenger4j#25]
There is an Exception when using the Library, see https://labsai.atlassian.net/browse/EDDI-22 for further details: 
[...]
Caused by: java.lang.NullPointerException
        at okhttp3.internal.tls.TrustRootIndex$BasicTrustRootIndex.<init>(TrustRootIndex.java:90) ~[okhttp-3.4.1.jar:?]
        at okhttp3.internal.tls.TrustRootIndex.get(TrustRootIndex.java:48) ~[okhttp-3.4.1.jar:?]
        at okhttp3.internal.tls.TrustRootIndex.get(TrustRootIndex.java:43) ~[okhttp-3.4.1.jar:?]
        at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:147) ~[okhttp-3.4.1.jar:?]
        at okhttp3.internal.tls.CertificateChainCleaner.get(CertificateChainCleaner.java:41) ~[okhttp-3.4.1.jar:?]
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:230) ~[okhttp-3.4.1.jar:?]
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:203) ~[okhttp-3.4.1.jar:?]
        at com.github.messenger4j.common.DefaultMessengerHttpClient.<init>(DefaultMessengerHttpClient.java:18) ~[messenger4j-0.8.0.jar:?]
        at com.github.messenger4j.common.MessengerRestClientAbstract.<init>(MessengerRestClientAbstract.java:26) ~[messenger4j-0.8.0.jar:?]
        at com.github.messenger4j.send.MessengerSendClientImpl.<init>(MessengerSendClientImpl.java:29) ~[messenger4j-0.8.0.jar:?]
        at com.github.messenger4j.send.MessengerSendClientBuilder.build(MessengerSendClientBuilder.java:26) ~[messenger4j-0.8.0.jar:?]
[...]

**Comment by maxgrabenhorst** [comment]
Had a short look at the stacktrace but seems to be a okhttp or configuration issue.
messenger4j 1.0.0-M1 with a updated version of okhttp is out. You could try if this works.
If you still have these issue we could consider to make the default http client implementation configurable or allow to pass in a preconfigured okHttp client.
