### ISSUE TITLE
null pointer exception with the following stacktrace

### ISSUE THREAD

**Issue by rahultokase** [messenger4j/messenger4j#33]
Hi
I am using 0.8.0 api and getting null pointer exception with the following stacktrace,

017-11-05T14:00:21.313255+00:00 heroku[router]: at=info method=POST path="/callback" host=rahulchatapp.herokuapp.com request_id=44db3095-a6e1-4a8b-8500-36d19a10ad4c fwd="31.13.114.72" dyno=web.1 connect=0ms service=45ms status=500 bytes=327 protocol=https
2017-11-05T14:00:21.282128+00:00 app[web.1]: 2017-11-05 14:00:21.280 ERROR 4 --- [io-27337-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
2017-11-05T14:00:21.282136+00:00 app[web.1]: 
2017-11-05T14:00:21.282138+00:00 app[web.1]: java.lang.NullPointerException: null
2017-11-05T14:00:21.282139+00:00 app[web.1]: 	at com.github.messenger4j.receive.MessengerReceiveClientImpl.processEntry(MessengerReceiveClientImpl.java:150) ~[messenger4j-0.8.0.jar!/:na]
2017-11-05T14:00:21.282139+00:00 app[web.1]: 	at com.github.messenger4j.receive.MessengerReceiveClientImpl.processCallbackPayload(MessengerReceiveClientImpl.java:144) ~[messenger4j-0.8.0.jar!/:na]

**Comment by maxgrabenhorst** [comment]
Seems to me that the incoming request payload is invalid.
Could you provide the anonymized incoming JSON?
I assume that the 'messaging' property is missing.

**Comment by maxgrabenhorst** [comment]
Still relevant? If so please reopen.
