### ISSUE TITLE
SenderAction issue

### ISSUE THREAD

**Issue by uugan** [messenger4j/messenger4j#37]
version: 1.0.0-M1

final SenderAction senderAction = SenderAction.MARK_SEEN;
SenderActionPayload payload = SenderActionPayload.create(recipientId, senderAction);
messenger.send(payload);

Gives error like below:
java.lang.IllegalArgumentException
	at com.github.messenger4j.send.MessageResponseFactory$$Lambda$502/1252459273.get(Unknown Source)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.github.messenger4j.send.MessageResponseFactory.create(MessageResponseFactory.java:24)
	at com.github.messenger4j.Messenger$$Lambda$499/2005040713.apply(Unknown Source)
	at com.github.messenger4j.Messenger.doRequest(Messenger.java:203)
	at com.github.messenger4j.Messenger.send(Messenger.java:120)

**Comment by maxgrabenhorst** [comment]
Already fixed with `1.0.0-M2` 👍

**Comment by uugan** [comment]
i'm using M2 but still

SenderActionPayload(super=Payload(recipient=IdRecipient(id=<USER_ID>), notificationType=Optional.empty), senderAction=MARK_SEEN)
: java.lang.IllegalArgumentException
	at com.github.messenger4j.send.MessageResponseFactory$$Lambda$905/2074964840.get(Unknown Source)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.github.messenger4j.send.MessageResponseFactory.create(MessageResponseFactory.java:24)
	at com.github.messenger4j.Messenger$$Lambda$900/530879185.apply(Unknown Source)
	at com.github.messenger4j.Messenger.doRequest(Messenger.java:203)
	at com.github.messenger4j.Messenger.send(Messenger.java:120)

**Comment by maxgrabenhorst** [comment]
Please clear your caches and try again. This error (line 24 in MessageResponseFactory) cannot occur anymore.
