### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by uugan** [messenger4j/messenger4j#88]
We put chat extension on our website but it gives error like below (v1.0.0-M3):
```
	at com.github.messenger4j.webhook.factory.ReferralEventFactory$$Lambda$839/1774598262.get(Unknown Source)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.github.messenger4j.webhook.factory.ReferralEventFactory.createReferralFromJson(ReferralEventFactory.java:51)
	at com.github.messenger4j.webhook.factory.PostbackEventFactory$$Lambda$750/434038658.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at com.github.messenger4j.webhook.factory.PostbackEventFactory.createEventFromJson(PostbackEventFactory.java:46)
	at com.github.messenger4j.webhook.factory.PostbackEventFactory.createEventFromJson(PostbackEventFactory.java:26)
	at com.github.messenger4j.webhook.factory.EventFactory.createEvent(EventFactory.java:42)
	at com.github.messenger4j.Messenger.onReceiveEvents(Messenger.java:150)
```

received json:
```
{"object":"page","entry":[{"id":"44234924xxx","time":1526280238913,"messaging":[{"recipient":{"id":"442349245xxx"},"timestamp":1526280238913,"sender":{"id":"1473036616xxx"},"postback":
{"payload":"x","referral":{"source":"CUSTOMER_CHAT_PLUGIN"},"title":"BLABLA"}}]}]}
```
its because of parsing referral.

**Comment by PhantomYdn** [comment]
Having the same issue:

```
java.lang.IllegalArgumentException
at java.util.Optional.orElseThrow(Optional.java:290)
at com.github.messenger4j.webhook.factory.BaseEventFactory.createReferralFromJson(BaseEventFactory.java:36)
at java.util.Optional.map(Optional.java:215)
at com.github.messenger4j.webhook.factory.PostbackEventFactory.createEventFromJson(PostbackEventFactory.java:47)
at com.github.messenger4j.webhook.factory.PostbackEventFactory.createEventFromJson(PostbackEventFactory.java:28)
at com.github.messenger4j.webhook.factory.EventFactory.createEvent(EventFactory.java:43)
at com.github.messenger4j.Messenger.onReceiveEvents(Messenger.java:150)
```

JSON:
```
{"object":"page","entry":[{"id":"850266978438247","time":1528510007079,"messaging":[{"recipient":{"id":"850266978438247"},"timestamp":1528510007079,"sender":{"id":"1765720756792314"},"postback":{"payload":"Kitchen A","referral":{"source":"CUSTOMER_CHAT_PLUGIN"},"title":"Kitchen A"}}]}]}
```

It seems that Facebook is sending just "referral":{"source":"CUSTOMER_CHAT_PLUGIN"} if message was sent from the site chat, but library expecting attribute `type` as mandatory.
