### ISSUE TITLE
Webhooks test on fb data: java.lang.IllegalArgumentException: null

### ISSUE THREAD

**Issue by jjcosare** [messenger4j/messenger4j#96]
Exception occurs on EchoEvent with missing appId

Request Payload from test version v2.11:
`{"entry": [{"changes": [{"field": "messages", "value": {"page_id": "1067280970047460"}}], "id": "0", "time": 1529127006}], "object": "page"}`

Exception:
`java.lang.IllegalArgumentException: null
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_171]
	at com.github.messenger4j.webhook.factory.MessageEchoEventFactory.createEventFromJson(MessageEchoEventFactory.java:43) ~[messenger4j-1.0.0.jar:na]
	at com.github.messenger4j.webhook.factory.MessageEchoEventFactory.createEventFromJson(MessageEchoEventFactory.java:25) ~[messenger4j-1.0.0.jar:na]
	at com.github.messenger4j.webhook.factory.EventFactory.createEvent(EventFactory.java:43) ~[messenger4j-1.0.0.jar:na]`

Also have tried to update appId as Optional but another exception occurs

Exception 1
`java.lang.IllegalArgumentException: null
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_171]
	at com.github.messenger4j.Messenger.onReceiveEvents(Messenger.java:148) ~[messenger4j-1.0.0.jar:na]
	at com.github.messenger4j.quickstart.boot.MessengerPlatformCallbackHandler.handleCallback(MessengerPlatformCallbackHandler.java:126) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.23.jar:8.5.23]`

Exception 2
`com.github.messenger4j.exception.MessengerApiException: Unsupported post request. Object with ID 'me' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api
	at com.github.messenger4j.exception.MessengerApiExceptionFactory.create(MessengerApiExceptionFactory.java:29) ~[messenger4j-1.0.0.jar:na]
	at com.github.messenger4j.Messenger.doRequest(Messenger.java:205) ~[messenger4j-1.0.0.jar:na]
	at com.github.messenger4j.Messenger.send(Messenger.java:120) ~[messenger4j-1.0.0.jar:na]`

**Comment by RomanNagornyi** [comment]
I have the same issue
